name: Publish package on npm

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (major, minor, patch)"
        required: true
        default: "patch"
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: yarn.lock
      - name: Update version
        working-directory: .
        id: version
        run: |
          if [[ ${{ github.event.inputs.release_type }} == "major" ]]; then
            echo "VERSION=$(npm version major)" >> $GITHUB_ENV
          elif [[ ${{ github.event.inputs.release_type }} == "minor" ]]; then
            echo "VERSION=$(npm version minor)" >> $GITHUB_ENV
          else
            echo "VERSION=$(npm version patch)" >> $GITHUB_ENV
          fi
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
      - name: Build
        run: yarn build
      - name: Publish
        run:
      - name: Tag and commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Arjo van Ramshorst (gh-actions)
          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: arjovanramshorst@gmail.com

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: user_info
          pull: '--rebase --autostash'

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "CI | Publish package:${{ env.VERSION }}"

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          tag: "release/${{ env.VERSION }}"
